
name: UnitTests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1.0'

      - name: Ls Directory
        run: ls -al

      - name: Move Directory
        run: cd Unit/UnitTestApp01

      - name: Ls Directory
        run: ls -al

      - name: UnitTests
        run: xcodebuild test -scheme UnitTestApp01 -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 12,OS=16.1'

      - name: UITests
        run: xcodebuild test -scheme UITests -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 12,OS=16.
